[versions]
androidGradlePlugin = "8.9.0"
appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.2.1"
junit = "4.13.2"
extJunit = "1.2.1"
espressoCore = "3.6.1"
glide = "4.16.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
junit = { module = "junit:junit", version.ref = "junit" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "extJunit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }